/**
 * Lead Database — Core (schema, CRUD, stats)
 */
const all = require('./_all');

module.exports = {
  getDb: all.getDb,
  upsertLead: all.upsertLead,
  batchUpsert: all.batchUpsert,
  findExistingLead: all.findExistingLead,
  recordScrapeRun: all.recordScrapeRun,
  getStats: all.getStats,
  getLeadById: all.getLeadById,
  updateLead: all.updateLead,
  deleteLeads: all.deleteLeads,
  bulkUpdateLeads: all.bulkUpdateLeads,
  exportLeads: all.exportLeads,
  getStateCoverage: all.getStateCoverage,
  getScrapeHistory: all.getScrapeHistory,
  getRecommendations: all.getRecommendations,
  shareFirmData: all.shareFirmData,
  deduceWebsitesFromEmail: all.deduceWebsitesFromEmail,
  getRecentActivity: all.getRecentActivity,
  getDistinctPracticeAreas: all.getDistinctPracticeAreas,
  getDistinctTags: all.getDistinctTags,
  tagLeads: all.tagLeads,
  getDailyGrowth: all.getDailyGrowth,
  getFieldCompleteness: all.getFieldCompleteness,
  getLeadsNeedingEmail: all.getLeadsNeedingEmail,
  updateEmailVerification: all.updateEmailVerification,
  getScraperHealth: all.getScraperHealth,
  getEnrichmentStats: all.getEnrichmentStats,
  getActivityFeed: all.getActivityFeed,
  getDistinctSources: all.getDistinctSources,
  getStateDetails: all.getStateDetails,
  PIPELINE_STAGES: all.PIPELINE_STAGES,
  getTableConfig: all.getTableConfig,
  saveTableConfig: all.saveTableConfig,
  getKanbanData: all.getKanbanData,
  getCardViewData: all.getCardViewData,
  computeWarmUpScore: all.computeWarmUpScore,
  batchComputeWarmUp: all.batchComputeWarmUp,
  getRecentAdmissions: all.getRecentAdmissions,
  getAdmissionSignals: all.getAdmissionSignals,
};
