/**
 * Lead Database — Quality checks, freshness, change detection, import/export
 */
const all = require('./_all');

module.exports = {
  runQualityChecks: all.runQualityChecks,
  getQualityAlerts: all.getQualityAlerts,
  resolveAlert: all.resolveAlert,
  getAlertSummary: all.getAlertSummary,
  getDatabaseHealth: all.getDatabaseHealth,
  getTopFirms: all.getTopFirms,
  findSimilarLeads: all.findSimilarLeads,
  detectChanges: all.detectChanges,
  getRecentChanges2: all.getRecentChanges2,
  getFirmChanges: all.getFirmChanges,
  getLeadChangeHistory: all.getLeadChangeHistory,
  getStalenessReport: all.getStalenessReport,
  previewImportMapping: all.previewImportMapping,
  importLeads: all.importLeads,
  getImportFieldMapping: all.getImportFieldMapping,
  getDataQualityReport: all.getDataQualityReport,
  getDataQualitySummary: all.getDataQualitySummary,
  recordFieldVerification: all.recordFieldVerification,
  getFreshnessReport: all.getFreshnessReport,
  getLeadFreshness: all.getLeadFreshness,
  logChange: all.logChange,
  getLeadChangelog: all.getLeadChangelog,
  getRecentChanges: all.getRecentChanges,
  recordExport: all.recordExport,
  getExportHistory: all.getExportHistory,
  getExportProfiles: all.getExportProfiles,
  createExportProfile: all.createExportProfile,
  deleteExportProfile: all.deleteExportProfile,
  runExportProfile: all.runExportProfile,
  getExportTemplates: all.getExportTemplates,
  createExportTemplate: all.createExportTemplate,
  deleteExportTemplate: all.deleteExportTemplate,
  getQualityRules: all.getQualityRules,
  createQualityRule: all.createQualityRule,
  deleteQualityRule: all.deleteQualityRule,
  runQualityRules: all.runQualityRules,
};
