/**
 * Lead Database — Lists, pipeline, sequences, campaigns, territories, routing
 */
const all = require('./_all');

module.exports = {
  createList: all.createList,
  getLists: all.getLists,
  getList: all.getList,
  updateList: all.updateList,
  deleteList: all.deleteList,
  addToList: all.addToList,
  removeFromList: all.removeFromList,
  getLeadLists: all.getLeadLists,
  getPipelineStats: all.getPipelineStats,
  getLeadsByStage: all.getLeadsByStage,
  moveLeadToStage: all.moveLeadToStage,
  bulkMoveToStage: all.bulkMoveToStage,
  getSequences: all.getSequences,
  createSequence: all.createSequence,
  addSequenceStep: all.addSequenceStep,
  deleteSequence: all.deleteSequence,
  enrollInSequence: all.enrollInSequence,
  getSequenceEnrollments: all.getSequenceEnrollments,
  renderSequenceStep: all.renderSequenceStep,
  getCampaigns: all.getCampaigns,
  createCampaign: all.createCampaign,
  deleteCampaign: all.deleteCampaign,
  addLeadsToCampaign: all.addLeadsToCampaign,
  getCampaignLeads: all.getCampaignLeads,
  updateCampaignStatus: all.updateCampaignStatus,
  getTerritories: all.getTerritories,
  createTerritory: all.createTerritory,
  deleteTerritory: all.deleteTerritory,
  assignLeadsToTerritory: all.assignLeadsToTerritory,
  getTerritoryLeads: all.getTerritoryLeads,
  getRoutingRules: all.getRoutingRules,
  createRoutingRule: all.createRoutingRule,
  deleteRoutingRule: all.deleteRoutingRule,
  runRoutingRules: all.runRoutingRules,
  recordStageTransition: all.recordStageTransition,
  getLifecycleAnalytics: all.getLifecycleAnalytics,
  getLeadLifecycle: all.getLeadLifecycle,
  recordSequenceEvent: all.recordSequenceEvent,
  getSequenceAnalytics: all.getSequenceAnalytics,
  getAllSequencePerformance: all.getAllSequencePerformance,
  getContactTimeline: all.getContactTimeline,
  logContact: all.logContact,
  getContactStats: all.getContactStats,
  getRecentContacts: all.getRecentContacts,
  getSchedules: all.getSchedules,
  createSchedule: all.createSchedule,
  updateSchedule: all.updateSchedule,
  deleteSchedule: all.deleteSchedule,
  markScheduleRun: all.markScheduleRun,
  getDueSchedules: all.getDueSchedules,
  getSequenceTemplates: all.getSequenceTemplates,
  createSequenceTemplate: all.createSequenceTemplate,
  updateSequenceTemplate: all.updateSequenceTemplate,
  deleteSequenceTemplate: all.deleteSequenceTemplate,
  renderSequenceTemplate: all.renderSequenceTemplate,
  getNurtureCadence: all.getNurtureCadence,
  getCadenceAnalytics: all.getCadenceAnalytics,
  getExportSchedules: all.getExportSchedules,
  createExportSchedule: all.createExportSchedule,
  deleteExportSchedule: all.deleteExportSchedule,
  runExportSchedule: all.runExportSchedule,
};
