/**
 * Lead Database — Lead scoring, ICP, confidence, activity, decay
 */
const all = require('./_all');

module.exports = {
  computeLeadScore: all.computeLeadScore,
  batchScoreLeads: all.batchScoreLeads,
  getScoreDistribution: all.getScoreDistribution,
  getScoringRules: all.getScoringRules,
  updateScoringRule: all.updateScoringRule,
  addScoringRule: all.addScoringRule,
  deleteScoringRule: all.deleteScoringRule,
  getScoreBreakdown: all.getScoreBreakdown,
  computeConfidenceScore: all.computeConfidenceScore,
  batchComputeConfidence: all.batchComputeConfidence,
  getConfidenceDistribution: all.getConfidenceDistribution,
  getIcpCriteria: all.getIcpCriteria,
  addIcpCriterion: all.addIcpCriterion,
  deleteIcpCriterion: all.deleteIcpCriterion,
  updateIcpCriterion: all.updateIcpCriterion,
  computeIcpScore: all.computeIcpScore,
  batchComputeIcpScores: all.batchComputeIcpScores,
  getIcpDistribution: all.getIcpDistribution,
  applyScoreDecay: all.applyScoreDecay,
  getDecayPreview: all.getDecayPreview,
  getScoringModels: all.getScoringModels,
  createScoringModel: all.createScoringModel,
  activateScoringModel: all.activateScoringModel,
  deleteScoringModel: all.deleteScoringModel,
  applyCustomScoring: all.applyCustomScoring,
  computeActivityScore: all.computeActivityScore,
  batchActivityScores: all.batchActivityScores,
  getActivityScoreConfig: all.getActivityScoreConfig,
  updateActivityScoreConfig: all.updateActivityScoreConfig,
  getDecayConfig: all.getDecayConfig,
  updateDecayConfig: all.updateDecayConfig,
  runScoreDecay: all.runScoreDecay,
  getDecayPreview2: all.getDecayPreview2,
};
